# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtf < Formula
  desc "A terminal UI for managing git worktrees"
  homepage "https://github.com/cKreymborg/git-treeflow"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.4.0/gtf_darwin_amd64.tar.gz"
      sha256 "e4c20c5a49d757411935fad94a96f20b28144e65cd7255f5c9a98e7fa4679736"

      define_method(:install) do
        bin.install "gtf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.4.0/gtf_darwin_arm64.tar.gz"
      sha256 "ecf97d3e5ad1c16a1c225f979fe84c85b2750b9e76d6d9fe679b43618f893881"

      define_method(:install) do
        bin.install "gtf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.4.0/gtf_linux_amd64.tar.gz"
      sha256 "832bd20aa9bbb5ffac7d5a5a3935a034c303a5325829a46957e501370f3ae15c"
      define_method(:install) do
        bin.install "gtf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.4.0/gtf_linux_arm64.tar.gz"
      sha256 "973a0e949ffd7f20a6e7b7a3c5dba56ecc94dc4877e12b253b18fc5185ef6a1d"
      define_method(:install) do
        bin.install "gtf"
      end
    end
  end

  def caveats
    <<~EOS
      To enable worktree switching (cd), add to your shell config:

        zsh:  eval "$(gtf --init zsh)"     # ~/.zshrc
        bash: eval "$(gtf --init bash)"    # ~/.bashrc
        fish: gtf --init fish | source     # ~/.config/fish/config.fish
    EOS
  end

  test do
    system "#{bin}/gtf", "--version"
  end
end
