# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtf < Formula
  desc "A terminal UI for managing git worktrees"
  homepage "https://github.com/cKreymborg/git-treeflow"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.2.1/gtf_darwin_amd64.tar.gz"
      sha256 "24b95459f9636c15cc3435aef24371af963a90f6cc029ed65cd7593c9da45b18"

      define_method(:install) do
        bin.install "gtf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.2.1/gtf_darwin_arm64.tar.gz"
      sha256 "18a29894890368b80efceb2b8538e5ba2219e3b26525460140cf189035d55e15"

      define_method(:install) do
        bin.install "gtf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.2.1/gtf_linux_amd64.tar.gz"
      sha256 "d099d5dbe191a0c918b1a921e92d2028febb1c5c6559b6695252880845e332d9"
      define_method(:install) do
        bin.install "gtf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.2.1/gtf_linux_arm64.tar.gz"
      sha256 "fb46074155b22808aa8691c16c7b4e294149d3dca585f9c8e6a91cc4fae6487e"
      define_method(:install) do
        bin.install "gtf"
      end
    end
  end

  def caveats
    <<~EOS
      To enable worktree switching (cd), add to your shell config:

        zsh:  eval "$(gtf --init zsh)"     # ~/.zshrc
        bash: eval "$(gtf --init bash)"    # ~/.bashrc
        fish: gtf --init fish | source     # ~/.config/fish/config.fish
    EOS
  end

  test do
    system "#{bin}/gtf", "--version"
  end
end
