# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtf < Formula
  desc "A terminal UI for managing git worktrees"
  homepage "https://github.com/cKreymborg/git-treeflow"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.3.0/gtf_darwin_amd64.tar.gz"
      sha256 "e9635a6d6cc4cb0728bedd31ff18285c8b0584320739bc2a489f6d988fd2bee3"

      define_method(:install) do
        bin.install "gtf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.3.0/gtf_darwin_arm64.tar.gz"
      sha256 "42cbfe272c1612ad9da42d74cc9530dd2267f7c78df6274085352c3538273f50"

      define_method(:install) do
        bin.install "gtf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.3.0/gtf_linux_amd64.tar.gz"
      sha256 "37188b295abfa1b7312f9923396c602953e67ea48cff94017361b75261561e0c"
      define_method(:install) do
        bin.install "gtf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cKreymborg/git-treeflow/releases/download/v0.3.0/gtf_linux_arm64.tar.gz"
      sha256 "2bf9a3d36297b74374bd2c7dfd8ffb13c12d390633c75f49c4228dadf4e7182d"
      define_method(:install) do
        bin.install "gtf"
      end
    end
  end

  def caveats
    <<~EOS
      To enable worktree switching (cd), add to your shell config:

        zsh:  eval "$(gtf --init zsh)"     # ~/.zshrc
        bash: eval "$(gtf --init bash)"    # ~/.bashrc
        fish: gtf --init fish | source     # ~/.config/fish/config.fish
    EOS
  end

  test do
    system "#{bin}/gtf", "--version"
  end
end
